controllers/AlquilanController.php
<?php

namespace app\controllers;

use app\models\Alquilan;
use app\models\Coches;
use app\models\Clientes;
use app\models\Seguros;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use Yii;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use yii\web\Response;


/**
 * AlquilanController implements the CRUD actions for Alquilan model.
 */
class AlquilanController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Alquilan models.
     *
     * @return string
     */
    public function actionIndex($dni_cliente = null)
    {
        $searchModel = new Alquilan(); //Buscador
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $dni_cliente);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Alquilan model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Alquilan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */

    
    public function actionCreate()
    {
        $model = new Alquilan();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                //Convertir las fechas al formato correcto
                $fecha1 = \DateTime::createFromFormat('d-m-Y', $model->fecha_inicio);
                $model->fecha_inicio = $fecha1->format('Y-m-d');
                $fecha2 = \DateTime::createFromFormat('d-m-Y', $model->fecha_fin);
                $model->fecha_fin = $fecha2->format('Y-m-d');
                
                if ($model->save(false)) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        } else {
            //Opciones del desplegable, guardarlas en un array
            $model->loadDefaultValues();
            $coches = Coches::find()
                ->joinWith('seguros')  
                ->where(['coches.estado' => 0])
                ->andWhere(['is not', 'seguros.matricula', null])  //Asegurarse de que la matricula no es nula en seguras
                ->all();
            
            $options = [];
            foreach ($coches as $coche) {
                $options[$coche->matricula] = [
                    'data-precio' => $coche->precio,
                    'label' => $coche->matricula . ' - ' . $coche->marca . ' ' . $coche->modelo
                ];
            }
            return $this->render('create', [
                'model' => $model,
                'options' => $options,
            ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Alquilan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
//    public function actionUpdate($id)
//    {
//        $model = $this->findModel($id);
//
//        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        }
//
//        return $this->render('update', [
//            'model' => $model,
//        ]);
//    }

    /**
     * Deletes an existing Alquilan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Alquilan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Alquilan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Alquilan::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    //Descargar un contrato en PDF
    public function actionDescargar($id) {
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        Yii::$app->response->headers->add('Content-Type', 'application/pdf');
        
        $model = Alquilan::findOne($id);

        //Verificar si el modelo se encontró correctamente
        if (!$model) {
            throw new NotFoundHttpException('El contrato solicitado no se ha encontrado.');
        }
        
        $coche = Coches::findOne(['matricula' => $model->matricula]);

        $cliente = Clientes::findOne(['dni' => $model->dni_cliente]);

        //Configura el PDF
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE,
            'destination' => Pdf::DEST_BROWSER,
            'content' => $this->renderPartial('descargaPdf', ['model' => $model,'coche' => $coche,'cliente' => $cliente,]),
            'methods' => [
                'SetTitle' => 'Descargar contrato',  
                'SetFooter' => ['|Página {PAGENO}|'],
            ]
        ]);

        return $pdf->render();
    }
    
    //Exportar los contratos a Excel
    public function actionExportar()
    {
        $contratos = Alquilan::find()->all();
        
        $spreadsheet = new Spreadsheet();
        
        //Crear una nueva hoja de cálculo
        $sheet = $spreadsheet->getActiveSheet();
        
        //Agregar encabezados
        $sheet->setCellValue('A1', 'ID');
        $sheet->setCellValue('B1', 'DNI Cliente');
        $sheet->setCellValue('C1', 'Matrícula');
        $sheet->setCellValue('D1', 'Fecha Inicio');
        $sheet->setCellValue('E1', 'Fecha Fin');
        $sheet->setCellValue('F1', 'Precio Total');
        
        //Establecer negrita para las celdas de la cabecera
        $boldFontStyle = [
            'font' => [
                'bold' => true,
            ],
        ];
        
        $sheet->getStyle('A1:F1')->applyFromArray($boldFontStyle);
        
        //Ajustar anchos de columnas
        $sheet->getColumnDimension('A')->setWidth(6);  //Ajustar el ancho de la columna A
        $sheet->getColumnDimension('B')->setWidth(15);  //Ajustar el ancho de la columna B
        $sheet->getColumnDimension('C')->setWidth(12);  //Ajustar el ancho de la columna C
        $sheet->getColumnDimension('D')->setWidth(12);  //Ajustar el ancho de la columna D
        $sheet->getColumnDimension('E')->setWidth(12);  //Ajustar el ancho de la columna E
        $sheet->getColumnDimension('F')->setWidth(10);  //Ajustar el ancho de la columna F

        //Agregar datos
        $row = 2;
        foreach ($contratos as $contrato) {
            $sheet->setCellValue('A' . $row, $contrato->id);
            $sheet->setCellValue('B' . $row, $contrato->dni_cliente);
            $sheet->setCellValue('C' . $row, $contrato->matricula);
            $sheet->setCellValue('D' . $row, date('d-m-Y', strtotime($contrato->fecha_inicio)));
            $sheet->setCellValue('E' . $row, date('d-m-Y', strtotime($contrato->fecha_fin)));
            $sheet->setCellValue('F' . $row, $contrato->precio_total);
            $row++;
        }
        
         //Establecer la ubicación de almacenamiento temporal
        $tempFilePath = Yii::getAlias('@app/runtime') . '/contratos.xlsx';
        
        //Crear el escritor
        $writer = new Xlsx($spreadsheet);
        
        //Guardar el archivo
        $writer->save($tempFilePath);
        
        //Descargar el archivo
        Yii::$app->response->sendFile($tempFilePath, 'contratos.xlsx')->send();
        unlink($tempFilePath); //Eliminar el archivo temporal
    }
    
    public function actionPrice()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $matricula = Yii::$app->request->post('matricula');
        $coche = Coches::findOne(['matricula' => $matricula]);

        if ($coche !== null) {
            return ['success' => true, 'precio' => $coche->precio];
        } else {
            return ['success' => false, 'message' => 'Vehículo no encontrado'];
        }
    }
  
}

controllers/ClientesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clientes;
use app\models\Telefonos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientesController implements the CRUD actions for Clientes model.
 */
class ClientesController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Clientes models.
     *
     * @return string
     */
    public function actionIndex($dni = null)
    {
        $searchModel = new Clientes(); //Buscador
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $dni);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Clientes model.
     * @param string $dni Dni
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($dni)
    {
        return $this->render('view', [
            'model' => $this->findModel($dni),
        ]);
    }

    /**
     * Creates a new Clientes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Clientes();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                //Convertir el formato de fecha adecuado
                $fecha = \DateTime::createFromFormat('d-m-Y', $model->fecha_permiso_conducir);
                $model->fecha_permiso_conducir = $fecha->format('Y-m-d');

                if ($model->save()) {
                    return $this->redirect(['telefonos/create', 'dni' => $model->dni]);
                }
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    /**
     * Updates an existing Clientes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $dni Dni
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($dni)
    {
        $model = $this->findModel($dni);

        if ($model->load(Yii::$app->request->post())) {
            //Convertir el formato de fecha adecuado
            $fecha = \DateTime::createFromFormat('d-m-Y', $model->fecha_permiso_conducir);
            if ($fecha) {
                $model->fecha_permiso_conducir = $fecha->format('Y-m-d');
            }

            if ($model->save()) {
                return $this->redirect(['telefonos/update', 'dni' => $model->dni]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Clientes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $dni Dni
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($dni)
    {
        $this->findModel($dni)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Clientes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $dni Dni
     * @return Clientes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($dni)
    {
        if (($model = Clientes::findOne(['dni' => $dni])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/descargaPresupuesto.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Presupuesto */

?>

<?= Html::img('@web/img/logotipo.png', ['id' => 'logoPDF', 'style' => 'float: right; width: 300px; margin: 12px;']) ?>

<div class="pdf-cabecera" style="margin-right: 40px; text-align: center; color: #858585">
    <br>Polígono Industrial de Candina, Nave 4
    <br>Santander, Cantabria
    <br>De lunes a sábado de 9:00 a 14:00
    <br>Teléfono 601472066 / 942710418
</div>

<h2 class="titulo" style="text-align: center;">Presupuesto</h2>

<p>
Datos del vehículo:
<br>
    <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Marca:</strong> <?= Html::encode($coche->marca) ?>
    <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Modelo:</strong> <?= Html::encode($coche->modelo) ?>
    <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Número de Matrícula:</strong> <?= Html::encode($model->matricula) ?>


    <br><br>El período de alquiler sería del <?= Yii::$app->formatter->asDate($model->fecha_inicio, 'dd') ?>-<?= Yii::$app->formatter->asDate($model->fecha_inicio, 'MM') ?>-<?= Yii::$app->formatter->asDate($model->fecha_inicio, 'yyyy') ?> y finalizará el <?= Yii::$app->formatter->asDate($model->fecha_fin, 'dd') ?>-<?= Yii::$app->formatter->asDate($model->fecha_fin, 'MM') ?>-<?= Yii::$app->formatter->asDate($model->fecha_fin, 'yyyy') ?>.
    <br><br>En caso de alquiler hay que tener en cuenta lo siguiente:
    <br><br><strong>1.Condiciones del Alquiler:</strong>
    <br><br>
    El Arrendatario se compromete a utilizar el vehículo exclusivamente para fines legales y de conformidad con las leyes de tránsito 
    locales. El Arrendatario asume la responsabilidad de cualquier daño causado al vehículo durante el período de alquiler, excepto por 
    desgaste normal. El Arrendatario se compromete a devolver el vehículo en las mismas condiciones en que lo recibió, salvo el desgaste 
    normal.<br><br>
    El Arrendatario se compromete a devolver el vehículo en la fecha y hora acordadas. Cualquier extensión del período de alquiler debe 
    ser acordada por escrito y estar sujeta a disponibilidad. El Arrendatario se compromete a pagar una tarifa de alquiler total de 
    <strong><?= Yii::$app->formatter->asCurrency($model->precio_total, 'EUR') ?> </strong> por el uso del vehículo durante el período acordado. <br><br>El Arrendatario se compromete a 
    pagar por cualquier costo adicional incurrido durante el período de alquiler, como multas de tráfico, peajes, o cargos por limpieza 
    excesiva. El Arrendatario debe ser mayor de 18 años y poseer una licencia de conducir válida y vigente en el 
    momento del alquiler.

    <br><br><strong>2. Responsabilidades del Arrendatario:</strong>

    <br><br>Durante el período de alquiler, el Arrendatario será responsable de mantener el vehículo en buen estado y de acuerdo con las leyes de tráfico locales. El Arrendatario también será responsable de pagar todos los peajes y multas de tráfico incurridos durante el uso del vehículo.

    <br><br><strong>3. Seguro y Responsabilidad:</strong>

    <br><br>El Arrendador proporciona seguro básico para el vehículo, que cubre daños a terceros y responsabilidad civil. El Arrendatario será responsable de cualquier daño al vehículo o a terceros que no esté cubierto por el seguro. Cualquier daño al vehículo se le cobrará al Arrendatario un extra según la gravedad.

    <br><br><strong>4. Restricciones de Uso:</strong>

    <br><br>El Arrendatario utilizará el vehículo únicamente para fines legales y dentro del área geográfica acordada. Se prohíbe el uso del vehículo para carreras, pruebas de velocidad o cualquier otra actividad ilegal.

    <br><br><strong>5. Devolución del Vehículo:</strong>

    <br><br>El Arrendatario devolverá el vehículo en la fecha y hora acordadas al final del período de alquiler. El Arrendador realizará una inspección del vehículo y resolverá cualquier disputa sobre daños o cargos adicionales.

    <br><br><strong>6. Resolución de Disputas:</strong>

    <br><br>Cualquier disputa relacionada con este contrato se resolverá mediante mediación, según las leyes del estado del Estado.
</p>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Presupuesto;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Presupuesto */
/* @var $options array */

$this->title = 'Auto Dani';

if (Yii::$app->session->hasFlash('presupuestoFormSubmitted')) {
    echo "<p>¡Presupuesto enviado exitosamente!</p>";
}
?>
<div class="homeGeneral container">
    <div class="row row-slider">
        <div class="col p-0">
            <div class="overlay"></div>
            <div class="carousel-overlay">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <?= Html::img('@web/img/homeImagen1.jpg', ['class' => 'd-block w-100', 'alt' => 'First slide']) ?>
                        </div>
                        <div class="carousel-item">
                            <?= Html::img('@web/img/homeImagen2.jpg', ['class' => 'd-block w-100', 'alt' => 'Second slide']) ?>
                        </div>
                        <div class="carousel-item">
                            <?= Html::img('@web/img/homeImagen3.jpg', ['class' => 'd-block w-100', 'alt' => 'Third slide']) ?>
                        </div>
                        <div class="carousel-item">
                            <?= Html::img('@web/img/homeImagen4.jpg', ['class' => 'd-block w-100', 'alt' => 'Quarter slide']) ?>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Anterior</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Siguiente</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="contenedor-tarjetas">
        <div class="card" style="width: 18rem;">
            <?= Html::img('@web/img/cliente.png', ['class' => 'd-block w-100 card-img-top img-cliente', 'alt' => 'Imagen cliente']) ?> 
            <div class="card-body pt-2">
                <?= Html::a('Nuevo Cliente', ['clientes/create'], ['class' => 'btn btn-success w-100 btn-cliente-home']) ?>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <?= Html::img('@web/img/contrato.png', ['class' => 'd-block w-100 card-img-top img-cliente', 'alt' => 'Imagen contrato']) ?> 
            <div class="card-body pt-2">
                <?= Html::a('Nuevo Contrato', ['alquilan/create'], ['class' => 'btn btn-success w-100 btn-cliente-home']) ?>
            </div>
        </div>
    </div>
    <div class="contenedor-abajo">
        <div class="row py-2">
            <div class="col-2"></div>
                <div class="col-8">
                    <h1 class="titulo-presupuesto">Generar presupuesto</h1> 

                    <?php $form = ActiveForm::begin([
                        'id' => 'presupuesto-form',
                    ]); ?>

                    <div class="form-inline-group-container">
                        <div class="form-inline-group">
                            <div class="form-group-inline">
                                <?= $form->field($model, 'matricula')->dropDownList(ArrayHelper::map($options, 'data-precio', 'label'), [
                                    'prompt' => 'Seleccione un coche',
                                    'id' => 'select-matricula-presupuesto',
                                    'style' => 'width: 320px;',
                                ])->label('Matrícula del coche') ?>
                            </div>

                            <?= Html::hiddenInput('Presupuesto[matricula]', '', ['id' => 'hidden-matricula-field-presupuesto']) ?>

                            <div class="form-group-inline">
                                <?= $form->field($model, 'fecha_inicio')->textInput([
                                    'value' => date('d-m-Y'), 
                                    'readonly' => true, 
                                    'style' => 'width: 230px;'
                                ])->label('Fecha de inicio') ?>
                            </div>

                            <div class="form-group-inline">
                                <?= $form->field($model, 'fecha_fin')->widget(\yii\jui\DatePicker::className(), [
                                    'dateFormat' => 'dd-MM-yyyy',
                                    'options' => ['class' => 'form-control', 'readonly' => true, 'style' => 'width: 230px;'],
                                    'clientOptions' => [
                                        'minDate' => 0, // Esto establece la mínima fecha seleccionable como la fecha actual
                                        'maxDate' => '+3m', // Esto establece la máxima fecha seleccionable como tres meses desde la fecha actual
                                        'changeMonth' => true,
                                        'changeYear' => true,
                                        'yearRange' => '-100:+2',
                                        'theme' => 'base',
                                        'placeholder' => 'Seleccione fecha',
                                        'beforeShowDay' => new \yii\web\JsExpression('
                                            function(date) {
                                                var day = date.getDay();
                                                return [(day != 0), ""];
                                            }
                                        ')
                                    ],
                                ])->label('Fecha de fin') ?>
                            </div>
             
                            <div class="form-group-inline">
                                <?= $form->field($model, 'precio_total')->textInput([
                                    'id' => 'precio-total', 
                                    'readonly' => true, 
                                    'style' => 'width: 320px;'
                                ]) ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-group text-center">
                        <?= Html::submitButton('Descargar Presupuesto', ['class' => 'btn btn-success btn-presupuesto']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>




            <div class="col-2"></div>
        </div>
    </div>
</div>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>