models/Alquilan.php
<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "alquilan".
 *
 * @property int $id
 * @property int $id_cliente
 * @property int $id_coche
 * @property string $fecha_inicio
 * @property string $fecha_fin
 * @property float $precio_total
 *
 * @property Clientes $cliente
 * @property Coches $coche
 */
class Alquilan extends \yii\db\ActiveRecord
{
    public $precio;

    public static function tableName()
    {
        return 'alquilan';
    }
    
    //Validaciones
    public function rules()
    {
        return [
            [['dni_cliente'], 'required', 'message' => 'Debe de seleccionar un cliente'],
            [['matricula'], 'required', 'message' => 'Debe de seleccionar una matrícula'],
            [['fecha_inicio'], 'required', 'message' => 'Debe de seleccionar una fecha'],
            [['fecha_fin'], 'required', 'message' => 'Debe de seleccionar una fecha'],
            [['precio_total'], 'required', 'message' => 'El precio no puede estar vácio'],
            [['fecha_inicio', 'fecha_fin'], 'safe'],
            [['precio_total'], 'number'],
            [['dni_cliente'], 'string', 'max' => 9],
            [['matricula'], 'string', 'max' => 7],
            [['dni_cliente', 'matricula'], 'unique', 'targetAttribute' => ['dni_cliente', 'matricula']],
            [['dni_cliente'], 'exist', 'skipOnError' => true, 'targetClass' => Clientes::class, 'targetAttribute' => ['dni_cliente' => 'dni']],
            [['matricula'], 'exist', 'skipOnError' => true, 'targetClass' => Coches::class, 'targetAttribute' => ['matricula' => 'matricula']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dni_cliente' => 'DNI / NIE Cliente',
            'matricula' => 'Matrícula',
            'fecha_inicio' => 'Fecha Inicio',
            'fecha_fin' => 'Fecha Fin',
            'precio_total' => 'Precio Total (€)',
        ];
    }

//    public function beforeSave($insert)
//    {
//        if (parent::beforeSave($insert)) {
//            $this->matricula = substr($this->matricula, 0, 7);
//            return true;
//        }
//        return false;
//    }

    public function getDniCliente()
    {
        return $this->hasOne(Clientes::class, ['dni' => 'dni_cliente']);
    }

    public function getMatricula0()
    {
        return $this->hasOne(Coches::class, ['matricula' => 'matricula']);
    }
    
    //Buscador
    public function search($dni_cliente)
    {
        $query = Alquilan::find();

        if (!is_null($dni_cliente)) {
            $query->andFilterWhere(['dni_cliente' => $dni_cliente]);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $dataProvider;
    }
    
}

controllers/AlquilanController.php
<?php

namespace app\controllers;

use app\models\Alquilan;
use app\models\Coches;
use app\models\Clientes;
use app\models\Seguros;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;
use Yii;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use yii\web\Response;


/**
 * AlquilanController implements the CRUD actions for Alquilan model.
 */
class AlquilanController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Alquilan models.
     *
     * @return string
     */
    public function actionIndex($dni_cliente = null)
    {
        $searchModel = new Alquilan(); //Buscador
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $dni_cliente);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Alquilan model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Alquilan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */

    
    public function actionCreate()
    {
        $model = new Alquilan();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                //Convertir las fechas al formato correcto
                $fecha1 = \DateTime::createFromFormat('d-m-Y', $model->fecha_inicio);
                $model->fecha_inicio = $fecha1->format('Y-m-d');
                $fecha2 = \DateTime::createFromFormat('d-m-Y', $model->fecha_fin);
                $model->fecha_fin = $fecha2->format('Y-m-d');
                
                if ($model->save(false)) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        } else {
            //Opciones del desplegable, guardarlas en un array
            $model->loadDefaultValues();
            $coches = Coches::find()
                ->joinWith('seguros')  
                ->where(['coches.estado' => 0])
                ->andWhere(['is not', 'seguros.matricula', null])  //Asegurarse de que la matricula no es nula en seguras
                ->all();
            
            $options = [];
            foreach ($coches as $coche) {
                $options[$coche->matricula] = [
                    'data-precio' => $coche->precio,
                    'label' => $coche->matricula . ' - ' . $coche->marca . ' ' . $coche->modelo
                ];
            }
            return $this->render('create', [
                'model' => $model,
                'options' => $options,
            ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Alquilan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
//    public function actionUpdate($id)
//    {
//        $model = $this->findModel($id);
//
//        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        }
//
//        return $this->render('update', [
//            'model' => $model,
//        ]);
//    }

    /**
     * Deletes an existing Alquilan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Alquilan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Alquilan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Alquilan::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    //Descargar un contrato en PDF
    public function actionDescargar($id) {
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        Yii::$app->response->headers->add('Content-Type', 'application/pdf');
        
        $model = Alquilan::findOne($id);

        //Verificar si el modelo se encontró correctamente
        if (!$model) {
            throw new NotFoundHttpException('El contrato solicitado no se ha encontrado.');
        }
        
        $coche = Coches::findOne(['matricula' => $model->matricula]);

        $cliente = Clientes::findOne(['dni' => $model->dni_cliente]);

        //Configura el PDF
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE,
            'destination' => Pdf::DEST_BROWSER,
            'content' => $this->renderPartial('descargaPdf', ['model' => $model,'coche' => $coche,'cliente' => $cliente,]),
            'methods' => [
                'SetTitle' => 'Descargar contrato',  
                'SetFooter' => ['|Página {PAGENO}|'],
            ]
        ]);

        return $pdf->render();
    }
    
    //Exportar los contratos a Excel
    public function actionExportar()
    {
        $contratos = Alquilan::find()->all();
        
        $spreadsheet = new Spreadsheet();
        
        //Crear una nueva hoja de cálculo
        $sheet = $spreadsheet->getActiveSheet();
        
        //Agregar encabezados
        $sheet->setCellValue('A1', 'ID');
        $sheet->setCellValue('B1', 'DNI Cliente');
        $sheet->setCellValue('C1', 'Matrícula');
        $sheet->setCellValue('D1', 'Fecha Inicio');
        $sheet->setCellValue('E1', 'Fecha Fin');
        $sheet->setCellValue('F1', 'Precio Total');
        
        //Establecer negrita para las celdas de la cabecera
        $boldFontStyle = [
            'font' => [
                'bold' => true,
            ],
        ];
        
        $sheet->getStyle('A1:F1')->applyFromArray($boldFontStyle);
        
        //Ajustar anchos de columnas
        $sheet->getColumnDimension('A')->setWidth(6);  //Ajustar el ancho de la columna A
        $sheet->getColumnDimension('B')->setWidth(15);  //Ajustar el ancho de la columna B
        $sheet->getColumnDimension('C')->setWidth(12);  //Ajustar el ancho de la columna C
        $sheet->getColumnDimension('D')->setWidth(12);  //Ajustar el ancho de la columna D
        $sheet->getColumnDimension('E')->setWidth(12);  //Ajustar el ancho de la columna E
        $sheet->getColumnDimension('F')->setWidth(10);  //Ajustar el ancho de la columna F

        //Agregar datos
        $row = 2;
        foreach ($contratos as $contrato) {
            $sheet->setCellValue('A' . $row, $contrato->id);
            $sheet->setCellValue('B' . $row, $contrato->dni_cliente);
            $sheet->setCellValue('C' . $row, $contrato->matricula);
            $sheet->setCellValue('D' . $row, date('d-m-Y', strtotime($contrato->fecha_inicio)));
            $sheet->setCellValue('E' . $row, date('d-m-Y', strtotime($contrato->fecha_fin)));
            $sheet->setCellValue('F' . $row, $contrato->precio_total);
            $row++;
        }
        
         //Establecer la ubicación de almacenamiento temporal
        $tempFilePath = Yii::getAlias('@app/runtime') . '/contratos.xlsx';
        
        //Crear el escritor
        $writer = new Xlsx($spreadsheet);
        
        //Guardar el archivo
        $writer->save($tempFilePath);
        
        //Descargar el archivo
        Yii::$app->response->sendFile($tempFilePath, 'contratos.xlsx')->send();
        unlink($tempFilePath); //Eliminar el archivo temporal
    }
    
    public function actionPrice()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $matricula = Yii::$app->request->post('matricula');
        $coche = Coches::findOne(['matricula' => $matricula]);

        if ($coche !== null) {
            return ['success' => true, 'precio' => $coche->precio];
        } else {
            return ['success' => false, 'message' => 'Vehículo no encontrado'];
        }
    }
  
}

views/alquilan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/** @var yii\web\View $this */
/** @var app\models\Alquilan $model */
/** @var array $options */ // Agregar esta línea
/** @var array $precios */ // Agregar esta línea

?>

<div class="alinear">
    <div class="alquilan-create">

        <h1><?= Html::encode($this->title) ?></h1>
        <br>

        <!-- Utiliza ActiveForm para el formulario -->
        <?php $form = ActiveForm::begin(); ?>
        
        <?= $form->field($model, 'dni_cliente')->dropDownList(
        \yii\helpers\ArrayHelper::map(
            \app\models\Clientes::find()->all(),
            'dni',
            function ($cliente) {
                return $cliente->dni . ' - ' . $cliente->nombre_completo;
            }
        ),
        ['prompt' => 'Selecciona un cliente']
        )->label('Cliente') ?>

        <!-- Agrega un campo de menú desplegable para la matrícula -->
        
        <?= $form->field($model, 'matricula')->dropDownList(ArrayHelper::map($options, 'data-precio', 'label'), [
            'prompt' => 'Seleccione un coche',
            'id' => 'select-matricula', // Agregar un ID al campo select
        ])->label('Matrícula del coche') ?>

        <!-- Agrega un campo para la fecha de inicio -->
        <?= $form->field($model, 'fecha_inicio')->textInput(['value' => date('d-m-Y'), 'readonly' => true])->label('Fecha de inicio') ?>

        <!-- Agrega un campo para la fecha de fin -->
        <?= $form->field($model, 'fecha_fin')->widget(\yii\jui\DatePicker::className(), [
            'dateFormat' => 'dd-MM-yyyy',
            'options' => ['class' => 'form-control', 'readonly' => true],
            'clientOptions' => [
                'minDate' => 0, // Esto establece la mínima fecha seleccionable como la fecha actual
                'changeMonth' => true, // Permite la selección directa del mes
                'changeYear' => true, // Permite la selección directa del año
                'yearRange' => '-100:+2', // Rango de años permitidos
                'theme' => 'base',
                'placeholder' => 'Seleccione fecha',
                'beforeShowDay' => new \yii\web\JsExpression('
                    function(date) {
                        var day = date.getDay();
                        return [(day != 0), ""];
                    }
                ')
            ],
        ])->label('Fecha de fin') ?>

        
        <?= $form->field($model, 'precio_total')->textInput(['id' => 'precio-total', 'readonly' => true]) ?>

        <!-- Agrega un botón para enviar el formulario -->
        <div class="form-group">
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        </div>

        <!-- Finaliza el formulario -->
        <?php ActiveForm::end(); ?>

    </div>
</div>

views/alquilan/_search.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<div class="matricula-form">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row contenedor-registro">
        <div class="col-md-8 contenedor-buscador">
            <?= $form->field($model, 'dni_cliente')->textInput(['maxlength' => true, 'placeholder' => 'Introduzca el DNI del cliente a buscar', 'style' => 'width: 293px;', 'autocomplete' => 'off'])->label(false) ?>
            <?php if ($model->hasErrors('dni_cliente')): ?>
                <div class="alert alert-danger" style="margin-top: 5px;">
                    <?= $model->getFirstError('dni_cliente') ?>
                </div>
            <?php endif; ?>
        </div>
    
        <div class="form-group" style="margin-left: 53px; margin-right: -22px;">
            <?= Html::submitButton('Buscar', ['class' => 'btn btn-secondary btn-buscador']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/alquilan/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Coches;
use app\models\Seguros;

/** @var yii\web\View $this */
/** @var app\models\Alquilan $model */
/** @var array $options */ // Agregar esta línea
/** @var array $precios */ // Agregar esta línea

$this->title = 'Nuevo Contrato';
$this->params['breadcrumbs'][] = ['label' => 'Alquilan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="alinear">
    <div class="alquilan-create">

        <h1><?= Html::encode($this->title) ?></h1>
        <br>

        <?php $form = ActiveForm::begin(); ?>
        
        <?= $form->field($model, 'dni_cliente')->dropDownList(
        \yii\helpers\ArrayHelper::map(
            \app\models\Clientes::find()->all(),
            'dni',
            function ($cliente) {
                return $cliente->dni . ' - ' . $cliente->nombre_completo;
            }
        ),
        ['prompt' => 'Selecciona un cliente', 'autocomplete' => 'off']
        )->label('Cliente') ?>
    
        <?= $form->field($model, 'matricula')->dropDownList(ArrayHelper::map($options, 'data-precio', 'label'), [
            'prompt' => 'Seleccione un coche',
            'id' => 'select-matricula', // Agregar un ID al campo select
            'autocomplete' => 'off'
        ])->label('Matrícula del coche') ?>
        
        <!--Campo oculto para la matricula-->
        <?= Html::hiddenInput('Alquilan[matricula]', '', ['id' => 'hidden-matricula-field']) ?>

        <?= $form->field($model, 'fecha_inicio')->textInput(['value' => date('d-m-Y'), 'readonly' => true])->label('Fecha de inicio') ?>

        <?= $form->field($model, 'fecha_fin')->widget(\yii\jui\DatePicker::classname(), [
            'dateFormat' => 'dd-MM-yyyy',
            'options' => ['class' => 'form-control', 'readonly' => true],
            'clientOptions' => [
                'minDate' => 0, //Esto establece la mínima fecha seleccionable como la fecha actual
                'maxDate' => '+3m', //Esto establece la máxima fecha seleccionable como tres meses desde la fecha actual
                'changeMonth' => true, //Permite la selección directa del mes
                'changeYear' => true, //Permite la selección directa del año
                'yearRange' => '-100:+2', //Rango de años permitidos
                'theme' => 'base',
                'placeholder' => 'Seleccione fecha',
                'autocomplete' => 'off',
                'beforeShowDay' => new \yii\web\JsExpression('
                    function(date) {
                        var day = date.getDay();
                        return [(day != 0), ""];
                    }
                ')
            ],
        ])->label('Fecha de fin') ?>
        
        <?= $form->field($model, 'precio_total')->textInput(['id' => 'precio-total', 'readonly' => true]) ?>

        <div class="form-group">
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        </div>

        <!-- Finaliza el formulario -->
        <?php ActiveForm::end(); ?>

    </div>
</div>

views/alquilan/index.php
<?php

use app\models\Alquilan;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Contratos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="alquilan-index">

    <h1 class="tituloTablas"><?= Html::encode($this->title) ?></h1>
    
    <div class="alinear-btn">
        <div class="contenedor-contrato">
            <?= Html::a('Nuevo Contrato', ['create'], ['class' => 'btn btn-success']) ?>
            <?= Html::a(
                '<img src="' . Yii::getAlias('@web') . '/img/export.png" />',
                ['exportar'], ['class' => 'btn-exportar', 'title' => 'Exportar a Excel']) ?>
        </div>
        <div class="row">
            <?php echo $this->render('_search', ['model' => $searchModel]); ?>        
        </div>
    </div>

    <?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [       
        [
            'label' => 'Cliente',
            'value' => function ($model) {
                return $model->dniCliente->nombre_completo;
            }
        ],
        [
            'attribute' => 'dni_cliente',
            'headerOptions' => ['style' => 'width: 180px;'],
        ],
        'matricula',
        [
            'attribute' => 'fecha_inicio',
            'format' => ['date', 'php:d-m-Y'], //Formato de fecha
        ],
        [
            'attribute' => 'fecha_fin',
            'format' => ['date', 'php:d-m-Y'],
        ],
        [
            'attribute' => 'precio_total',
            'value' => function ($model) {
                return strpos($model->precio_total, '.') !== false 
                    ? number_format($model->precio_total, 2, ',', '.') 
                    : number_format($model->precio_total, 0, ',', '.');
            },
            'format' => 'raw',
        ],
        ['class' => 'yii\grid\ActionColumn', 'template' => '{view} {delete}']
    ],
]); ?>

</div>

views/alquilan/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Alquilan $model */

$this->title = 'Actualizar Contrato';
$this->params['breadcrumbs'][] = ['label' => 'Alquilan', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="alinear">
    <div class="alquilan-update">

        <h1><?= Html::encode($this->title) ?></h1>

        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>

    </div>
</div>

views/alquilan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\mpdf\Pdf;

/** @var yii\web\View $this */
/** @var app\models\Alquilan $model */

$this->title = 'Contrato';
$this->params['breadcrumbs'][] = ['label' => 'Alquilan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="alinear">
    <div class="alquilan-view">
        <h1><?= Html::encode($this->title) ?></h1>

        <div class="contenedor">
            <div class="contenedor1-contratos">
                <?= //Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) 
                 Html::a('Eliminar', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => '¿Estás seguro de que quieres eliminar este registro?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>
            <div class="contenedor2-contratos">
                <?= Html::a('Descargar contrato', ['alquilan/descargar','id' => $model->id], [
                    'class' => 'btn btn-info', 
                    'target'=>'_blank', 
                    'data-toggle'=>'tooltip', 
                    'title'=>'Descarga el contrato en PDF'
                ]) ?>
            </div>
        </div>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'dni_cliente',
                [
                    'label' => 'Cliente',
                    'value' => function ($model) {
                        return $model->dniCliente->nombre_completo;
                    }
                ],
                'matricula',
                [
                    'label' => 'Marca',
                    'value' => function ($model) {
                        return $model->matricula0->marca;
                    }
                ],
                [
                    'label' => 'Modelo',
                    'value' => function ($model) {
                        return $model->matricula0->modelo;
                    }
                ],
                [
                    'attribute' => 'fecha_inicio',
                    'format' => ['date', 'php:d-m-Y'],
                ],
                [
                    'attribute' => 'fecha_fin',
                    'format' => ['date', 'php:d-m-Y'],
                ],              
                [
                    'attribute' => 'precio_total',
                    'value' => function ($model) {
                        return strpos($model->precio_total, '.') !== false 
                            ? number_format($model->precio_total, 2, ',', '.') 
                            : number_format($model->precio_total, 0, ',', '.');
                    },
                    'format' => 'raw',
                ],
                
            ],
        ]) ?>

    </div>
</div>